# Generated by Django 5.0.4 on 2026-03-22 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_phone_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notification_preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email_appointments', models.BooleanField(default=True)),
                ('email_billing', models.BooleanField(default=True)),
                ('email_notes', models.BooleanField(default=False)),
                ('sms_reminders', models.BooleanField(default=True)),
                ('auth_alerts', models.BooleanField(default=True)),
                ('denial_alerts', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
