# Generated by Django 5.0.4 on 2026-05-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_notification_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary billing location for the organization. Used as the Billing Provider address on claims and PDFs.'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='accounts_location_one_primary_per_org'),
        ),
    ]
