# Generated by Django 5.0.4 on 2026-05-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_location_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='npi',
            field=models.CharField(blank=True, default='', help_text='Individual (Type 1) NPI — 10 digits, Luhn-validated.', max_length=10),
        ),
    ]
