# Generated by Django 5.0.4 on 2026-05-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ein',
            field=models.CharField(blank=True, default='', help_text='9-digit EIN (digits only, no dashes). Used when a contractor bills under their own entity instead of the practice EIN.', max_length=9),
        ),
    ]
