# Generated by Django 5.0.4 on 2026-05-08 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0006_appointment_event_type_appointment_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_time', models.CharField(choices=[('48h', '48 hours before'), ('24h', '24 hours before'), ('2h', '2 hours before')], max_length=4)),
                ('scheduled_for', models.DateTimeField(help_text='UTC instant at which dispatch_due_reminders should pick this row up.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_flight', 'In flight'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', help_text='Provider that handled the send (stub, twilio).', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', help_text='External message ID from the SMS provider (e.g. Twilio SID).', max_length=128)),
                ('skip_reason', models.CharField(blank=True, choices=[('opted_out', 'Client opted out'), ('no_phone', 'No phone number on file'), ('invalid_phone', 'Phone failed E.164 parsing'), ('quiet_hours_stale', 'Quiet hours pushed past appointment'), ('past', 'Lead time was already past at scheduling'), ('non_session_event', 'Not a billable client session')], default='', max_length=32)),
                ('last_error', models.CharField(blank=True, default='', help_text='Truncated error category from the provider. No PHI.', max_length=255)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='scheduling.appointment')),
            ],
            options={
                'ordering': ['scheduled_for'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='msg_reminder_dispatch_idx'), models.Index(fields=['appointment'], name='messaging_a_appoint_f5673a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='appointmentreminder',
            constraint=models.UniqueConstraint(fields=('appointment', 'lead_time'), name='msg_reminder_appt_lead_uniq'),
        ),
    ]
