# Generated by Django 5.0.4 on 2026-02-20 22:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'ordering': ['-invoice_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(blank=True, default='', max_length=100)),
                ('payer_name', models.CharField(max_length=255)),
                ('payer_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('denied', 'Denied'), ('resubmitted', 'Resubmitted')], default='created', max_length=20)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insurance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('patient_responsibility', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('write_off_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, default='')),
                ('resubmission_count', models.IntegerField(default=0)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='clients.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='billing.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('units', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.appointment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.invoice')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(choices=[('payment', 'Payment'), ('write_off', 'Write-off'), ('adjustment', 'Adjustment')], default='payment', max_length=50)),
                ('payer_type', models.CharField(blank=True, choices=[('insurance', 'Insurance'), ('patient', 'Patient')], default='', max_length=50)),
                ('payment_method', models.CharField(blank=True, default='', max_length=50)),
                ('stripe_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.claim')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
            options={
                'ordering': ['-payment_date'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client'], name='billing_inv_client__70fb2b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='billing_inv_status_541249_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['client'], name='billing_cla_client__1f9bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='billing_cla_status_aea0b1_idx'),
        ),
    ]
