# Generated by Django 5.0.4 on 2026-03-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='resubmission_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
