# Generated by Django 5.0.4 on 2026-04-20 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_notification_preference'),
        ('billing', '0003_add_resubmission_notes_to_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='oa_claim_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='oa_file_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='oa_rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='oa_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='x12_837_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='OASubmissionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[('837p', '837P Claim File'), ('999', '999 Acknowledgement'), ('277ca', '277CA Claim Status'), ('835', '835 ERA Payment'), ('file_summary', 'File Summary')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('oa_file_id', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('partial', 'Partial'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('claim_count', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('raw_response', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oa_submission_logs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('payer_id', models.CharField(max_length=20)),
                ('transaction_type', models.CharField(blank=True, default='', max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('enrollment_required', models.BooleanField(default=False)),
                ('supports_837p', models.BooleanField(default=False)),
                ('supports_eligibility', models.BooleanField(default=False)),
                ('supports_era', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['payer_id'], name='billing_pay_payer_i_fc5260_idx')],
            },
        ),
    ]
