# Generated by Django 5.0.4 on 2026-04-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_oa_fields_payer_submissionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='transaction_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
