# Generated by Django 5.0.4 on 2026-04-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_payer_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='payer_id',
            field=models.CharField(max_length=40),
        ),
    ]
