# Generated by Django 5.0.4 on 2026-06-04 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_user_ein'),
        ('clients', '0005_client_sms_consent_obtained_at_and_more'),
        ('scheduling', '0006_appointment_event_type_appointment_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BLSClientPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bls_preference', to='clients.client')),
            ],
            options={
                'verbose_name': 'BLS Client Preference',
                'verbose_name_plural': 'BLS Client Preferences',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BLSOrgDefaults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bls_defaults', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'BLS Org Defaults',
                'verbose_name_plural': 'BLS Org Defaults',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BLSSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 hex digest of the signed token. The token itself is never stored.', max_length=64, unique=True)),
                ('token_claimed_at', models.DateTimeField(blank=True, help_text='Set when the client first opens the invite link. Used to enforce one-time claim.', null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('waiting_for_client', 'Waiting for client'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended'), ('abandoned', 'Abandoned')], db_index=True, default='created', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('pass_count', models.PositiveIntegerField(default=0)),
                ('set_count', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('modality', models.CharField(choices=[('visual_only', 'Visual only'), ('audio_only', 'Audio only'), ('both', 'Visual + audio')], default='both', max_length=16)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Optional — ad-hoc sessions launched outside the calendar leave this null.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bls_sessions', to='scheduling.appointment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_sessions', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bls_sessions_run', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BLS Session',
                'verbose_name_plural': 'BLS Sessions',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['client', '-created_at'], name='bls_session_client_history'), models.Index(fields=['therapist', '-created_at'], name='bls_session_therapist_act')],
            },
        ),
        migrations.AddConstraint(
            model_name='blssession',
            constraint=models.CheckConstraint(check=models.Q(('status', 'ended'), ('ended_at__isnull', True), _connector='OR'), name='bls_session_ended_at_only_when_ended'),
        ),
        migrations.AddConstraint(
            model_name='blssession',
            constraint=models.CheckConstraint(check=models.Q(('started_at__isnull', True), ('started_at__gte', models.F('created_at')), _connector='OR'), name='bls_session_started_after_created'),
        ),
    ]
