# Generated by Django 5.0.4 on 2026-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blssession',
            name='short_code',
            field=models.CharField(blank=True, db_index=True, help_text='Opaque 6-char alias for the signed token. URL-friendly.', max_length=12, null=True, unique=True),
        ),
    ]
