# Generated by Django 5.0.4 on 2026-02-21 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_notes', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_plans', to='clients.client'),
        ),
    ]
