# Generated by Django 5.0.4 on 2026-03-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_document_cloudinary_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cloudinary_public_id',
        ),
        migrations.AddField(
            model_name='document',
            name='s3_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
