# Generated by Django 5.0.4 on 2026-04-05 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_referral_source'),
        ('clinical', '0004_rename_cloudinary_to_s3'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_date', models.DateField()),
                ('intake_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('signed', 'Signed'), ('co_signed', 'Co-Signed')], default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('signature_data', models.TextField(blank=True, default='')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('co_signed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_signature', models.TextField(blank=True, default='')),
                ('client_signature', models.TextField(blank=True, default='')),
                ('client_signed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intake_assessments', to='clients.client')),
                ('co_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_signed_intakes', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assessment_date'],
                'abstract': False,
                'indexes': [models.Index(fields=['client'], name='clinical_in_client__38b121_idx'), models.Index(fields=['provider'], name='clinical_in_provide_6a3b37_idx')],
            },
        ),
    ]
