# Generated by Django 5.0.4 on 2026-04-06 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_intakeassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='co_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='co_signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cosigned_treatment_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='from_intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_plans', to='clinical.intakeassessment'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='plan_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='signature_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('signed', 'Signed'), ('co_signed', 'Co-Signed'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='supervisor_signature',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
