# Generated by Django 5.0.4 on 2026-05-05 07:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_treatmentplan_co_signed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(help_text='The amendment text. Required and immutable once written.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_addendums', to=settings.AUTH_USER_MODEL)),
                ('parent_intake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addendums', to='clinical.intakeassessment')),
                ('parent_session_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addendums', to='clinical.sessionnote')),
                ('parent_treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addendums', to='clinical.treatmentplan')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['parent_session_note', 'created_at'], name='clinical_ad_parent__cde281_idx'), models.Index(fields=['parent_intake', 'created_at'], name='clinical_ad_parent__df09e2_idx'), models.Index(fields=['parent_treatment_plan', 'created_at'], name='clinical_ad_parent__8bd8b7_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='addendum',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('parent_intake__isnull', True), ('parent_session_note__isnull', False), ('parent_treatment_plan__isnull', True)), models.Q(('parent_intake__isnull', False), ('parent_session_note__isnull', True), ('parent_treatment_plan__isnull', True)), models.Q(('parent_intake__isnull', True), ('parent_session_note__isnull', True), ('parent_treatment_plan__isnull', False)), _connector='OR'), name='addendum_exactly_one_parent'),
        ),
    ]
