# Generated by Django 5.0.4 on 2026-05-05 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_mrn'),
        ('clinical', '0007_addendum_addendum_addendum_exactly_one_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_date', models.DateTimeField(help_text='When the contact occurred (not when this note was written).')),
                ('contact_type', models.CharField(choices=[('phone_outbound', 'Phone (Outbound)'), ('phone_inbound', 'Phone (Inbound)'), ('voicemail_left', 'Voicemail Left'), ('email', 'Email'), ('text_message', 'Text Message'), ('missed_outreach', 'Missed-Appointment Outreach'), ('in_person_brief', 'In-Person (Brief)'), ('collateral', 'Collateral Contact'), ('other', 'Other')], max_length=32)),
                ('summary', models.TextField(help_text='Plain-text description of the contact.')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Optional — for tracking unbilled time (e.g. long phone consults).', null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_notes', to='clients.client')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_contact_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contact_date'],
                'abstract': False,
                'indexes': [models.Index(fields=['client', '-contact_date'], name='clinical_co_client__25df7e_idx'), models.Index(fields=['provider'], name='clinical_co_provide_4e02e4_idx')],
            },
        ),
    ]
