# Generated by Django 5.0.4 on 2026-04-06 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_notification_preference'),
        ('clients', '0003_client_mrn'),
        ('scheduling', '0002_alter_appointment_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Groups recurring appointment instances into a series', null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['service_code'], name='scheduling__service_047f41_idx'),
        ),
    ]
