# Generated by Django 5.0.4 on 2026-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_series_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='modifiers',
            field=models.CharField(blank=True, default='', help_text='CPT modifiers (e.g., -95 for telehealth, GO/GP/GN for therapy)', max_length=50),
        ),
    ]
