# Generated by Django 5.0.4 on 2026-04-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_add_modifiers_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='place_of_service',
            field=models.CharField(blank=True, default='11', help_text='Place of Service code (e.g., 11=Office, 02=Telehealth, 12=Home)', max_length=2),
        ),
    ]
