# Generated by Django 5.0.4 on 2026-05-07 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_npi'),
        ('clients', '0004_client_service_categories'),
        ('scheduling', '0005_add_place_of_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='event_type',
            field=models.CharField(choices=[('client_session', 'Client Session'), ('staff_meeting', 'Staff Meeting'), ('personal_block', 'Personal Block'), ('training', 'Training / CEU'), ('other', 'Other')], default='client_session', help_text='client_session is the only billable type. Others are calendar blocks only.', max_length=32),
        ),
        migrations.AddField(
            model_name='appointment',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Title shown for non-session events. Ignored for client sessions (client name is used).', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['event_type'], name='scheduling__event_t_91a0b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('client__isnull', False), ('event_type', 'client_session')), models.Q(models.Q(('event_type', 'client_session'), _negated=True), ('client__isnull', True)), _connector='OR'), name='appointment_client_matches_event_type'),
        ),
    ]
