# Generated by Django 5.0.4 on 2026-02-20 22:54

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=2)),
                ('zip_code', models.CharField(blank=True, default='', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('emergency_contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, default='', max_length=50)),
                ('insurance_primary_name', models.CharField(blank=True, default='', max_length=255)),
                ('insurance_primary_id', models.CharField(blank=True, default='', max_length=100)),
                ('insurance_primary_group', models.CharField(blank=True, default='', max_length=100)),
                ('insurance_secondary_name', models.CharField(blank=True, default='', max_length=255)),
                ('insurance_secondary_id', models.CharField(blank=True, default='', max_length=100)),
                ('diagnosis_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurance_name', models.CharField(max_length=255)),
                ('authorization_number', models.CharField(blank=True, default='', max_length=100)),
                ('service_code', models.CharField(blank=True, default='', max_length=50)),
                ('units_approved', models.IntegerField()),
                ('units_used', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_authorizations', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='clients.client')),
            ],
            options={
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization', 'last_name', 'first_name'], name='clients_cli_organiz_5188dc_idx'),
        ),
        migrations.AddIndex(
            model_name='authorization',
            index=models.Index(fields=['client', 'start_date', 'end_date'], name='clients_aut_client__ddceaa_idx'),
        ),
    ]
