# Generated by Django 5.0.4 on 2026-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='referral_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
