# Generated by Django 5.0.4 on 2026-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_referral_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mrn',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Auto-generated unique patient chart number', max_length=20, verbose_name='Medical Record Number'),
        ),
    ]
