# Generated by Django 5.0.4 on 2026-05-07 00:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_mrn'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='service_categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, help_text='Service categories this client is enrolled in (Psych, OT, Speech, etc.).', size=None),
        ),
    ]
