# Generated by Django 5.0.4 on 2026-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sms_consent_obtained_at',
            field=models.DateTimeField(blank=True, help_text='When the client consented to receive SMS reminders.', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='sms_reminders_enabled',
            field=models.BooleanField(default=False, help_text='Send SMS appointment reminders. Requires sms_consent_obtained_at.'),
        ),
    ]
