# Generated by Django 5.0.4 on 2026-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('auth_expiring', 'Authorization Expiring'), ('missing_note', 'Missing Note'), ('appointment_reminder', 'Appointment Reminder'), ('claim_denied', 'Claim Denied'), ('payment_received', 'Payment Received'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
